### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by cruftex** [streamx-co/FluentJPA#1]
> For example, if you are running FluentJPA on your server, to provide a SaaS services, you would have to give away all of your source code.

I think this does not hold, since your specific software is not meant to be used by a user over a network. Pls. double check. Also read the page you refer to:

https://www.gnu.org/licenses/why-affero-gpl.html

Which links to:
https://www.gnu.org/philosophy/who-does-that-server-really-serve.html

itext is an interesting example of an APGL library, where the AGPL approach for dual licensing seems to work. Maybe their approach works out since the (end) user gets the PDF and generating PDFs is an explicit function of the including software. So there is user interaction for the purpose of generating the PDF. 

I recommend to release the basic product simply under Apache and make money with addons, support and training. Even GPL is too restrictive and hinders adoption.

Sorry to bring this up as first issue. But I wouldn't make the effort, if I didn't see any potential here ;)

**Comment by kostat** [comment]
Thank you for raising this question.

The FluentJPA [license model](https://github.com/streamx-co/FluentJPA/wiki/License-Model) is very simple: if your software if free (GPL compatible), use our for free. Bit if our software makes money for you, we would like to be paid too.

AGPL is a well known license to back this principle legally. See [wikipedia article](https://en.wikipedia.org/wiki/Affero_General_Public_License). That's the reason we choose it.

But lets put the legal side apart. Our pricing is affordable. If FluentJPA helps you in your work, the price shouldn't be an issue. But it will support our work.

Last but not least, I believe that a good library should not require that much support to be a good source of revenue. I want that the license model will push us to make the most easy to use product possible!

**Comment by cruftex** [comment]
> The FluentJPA license model is very simple: if your software if free (GPL compatible), use our for free. But if our software makes money for you, we would like to be paid too.

I am not sure whether whether this was a simplification or you really mean it that way. There is no Open Source license (in terms of OSI compatible) that hinders you from using a software and making money with it.

> Last but not least, I believe that a good library should not require that much support to be a good source of revenue.

Ideally, yes!

Your software targets developer productivity. That means costs of using your library are well justified, when I save developer capacity and have a faster time to market. There are no benefits in operations, in terms of saving computing resources.

Its sad, I am more than willing to pay money for a reasonable offer, in relation of the value I get. Many Open Source projects and businesses don't have that.

Besides, I cannot find the terms of the commercial license.

There is a lot to discuss about OS licensing and I just remind that I had the first discussion about that topic 25 years ago. Most of the time those discussion were quite long and fruitless. To learn more about OS community and OS business models I can recommend the talks at FOSDEM, there are archived videos. See: https://archive.fosdem.org/2019/schedule/track/community_devroom/

You can try to find your way and learn from the experience of others. I wish the best of luck!
You can keep the issue open, maybe somebody else has to say something, or close it.

**Comment by kostat** [comment]
Our [commercial offering](https://fluentjpa.com/) is available [here](https://fluentjpa.com/). Potentially it's not easy enough to find. I will address that.

**Comment by cruftex** [comment]
I am not speaking about a commercial offering. I am speaking about a commercial license, this is a complete set of written words encompassing all legal obligations of the license provider and licensee.

**Comment by kostat** [comment]
Indeed this is not clear enough and should be addressed. I'm re-opening the case until this is fixed.

Generally the terms are best effort support and freedom from AGPL constrains for the period of the license.

Do you need a different SLA? Let me know

**Comment by kostat** [comment]
Commercial license has the terms of [GNU Lesser General Public License (LGPL)](https://www.gnu.org/licenses/lgpl-3.0.en.html). In other words, the project having a [valid commercial license](https://fluentjpa.com/pricing-faq), can use FluentJPA under LGPL license.

**Comment by kostat** [comment]
Our offering has changed. Now we provide a [Support Contract](https://fluentjpa.com/#fdb2faf1-b52e-4512-8064-7d1eca70b5ab), which lets you ask us to translate **any SQL** to FluentJPA within 5 business days SLA. There is a **Money Back Guarantee** if we miss this SLA!
