### ISSUE TITLE
Secondary packaging

### ISSUE THREAD

**Issue by CN-Henny** [streamx-co/FluentJPA#10]
I don't want to write FROM and SELECT every time. Can we packaging FluentJPA.SQL again. Only pass the WHERE condition and return a complete SQL statement

**Comment by CN-Henny** [comment]
![image](https://github.com/streamx-co/FluentJPA/assets/49507176/aff475b0-be51-4cf5-9804-23f33f4ed6f3)


For example, this

**Comment by kostat** [comment]
FluentJPA has a builtin library of useful shortcuts for repetitive cases (and you can write your own, of course) - https://github.com/streamx-co/FluentJPA/wiki/Library#selectall-selectmany. In this case you can use `selectAll()`:
```java
FluentJPA.SQL((T t) -> {
    selectAll(t);
    WHERE(a);
});
```

Does it address your question?

**Comment by CN-Henny** [comment]
Quote my picture：
if "a" type is func 
Pass in an LAMBDA when calling

![image](https://github.com/streamx-co/FluentJPA/assets/49507176/57c32afa-c181-4e9d-bb0f-3cd829f077b1)


![image](https://github.com/streamx-co/FluentJPA/assets/49507176/b1d36463-8617-4f1c-b230-818dce5d8aaa)

**Comment by kostat** [comment]
@CN-Henny 
Eventually this is supported, see https://github.com/streamx-co/FluentJPA/wiki/Dynamic-Queries.
In your example `WHERE()` is missing.
