### ISSUE TITLE
Unable to import subQuery() method

### ISSUE THREAD

**Issue by DheerajKN** [streamx-co/FluentJPA#3]
After going through the FluentJPA Implementation on DZone. I was able to import all the statements like FluentJPA, FluentSQL, But I was unable to import subQuery into my program we have installed only `fluent-jpa`

So we need to import another maven package to access subQuery method??

How to resolve this issue??

**Comment by kostat** [comment]
Yes, you need also `sql-grammar` dependency, see [setup](https://github.com/streamx-co/FluentJPA/wiki/Setup).
